Dashboard Microtech/Controllers/PreventiviController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft_Core.Database.Models;
using Microtech_Core.Database;
using Microtech_Core.Database.Functions;
using Microtech_Core.Database.Models;
using Microtech_Core.WebServices.Services;
using Microtech_Core.WebServices.Services.Misc.Utils;
using Microtech_Core.WebServices.Services.Pojo;
using Newtonsoft.Json;

namespace Dashboard_Microtech.Controllers
{
    public class PreventiviController : Controller
    {
        public IActionResult Index()
        {
            return View("Search", model: JsonConvert.DeserializeObject<Agent>(HttpContext.Session.GetString("Logged")));
        }

        public IActionResult ShowResultList([FromQuery]string cli, [FromQuery]string dateBeg, [FromQuery]string dateEnd)
        {
            var getLsOrd = new GetLsPreService(cli, "http://2.229.69.115:8015/www/dacgi/WSGetLsPre.pgm").getLSPreAsync();
            if (getLsOrd != null)
            {
                List<GetLsPre> filteredList = null;
            DateTime Beg = default(DateTime);
            DateTime End = default(DateTime);

            Customer customer = Utils.GetCustomerNameByCode(getLsOrd[0].delId.ToString());
            if (dateBeg != null)
            {
                Beg = DateTime.ParseExact(dateBeg, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }
            if (dateEnd != null)
            {
                End = DateTime.ParseExact(dateEnd, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }


            

                if (dateBeg != null && dateEnd == null)
                {
                    filteredList = getLsOrd.Where(i => DateTime.ParseExact(i.getDate(), "dd/MM/yyyy", CultureInfo.InvariantCulture) > Beg).ToList();
                }
                if (dateBeg == null && dateEnd != null)
                {
                    filteredList = getLsOrd.Where(i => DateTime.ParseExact(i.getDate(), "dd/MM/yyyy", CultureInfo.InvariantCulture) < End).ToList();
                }
                if (dateBeg != null && dateEnd != null)
                {
                    filteredList = getLsOrd.Where(i => DateTime.ParseExact(i.getDate(), "dd/MM/yyyy", CultureInfo.InvariantCulture) >= Beg && DateTime.ParseExact(i.getDate(), "dd/MM/yyyy", CultureInfo.InvariantCulture) <= End).ToList();
                }

                if (dateBeg == null && dateEnd == null)
                {
                    filteredList = getLsOrd;
                }
                filteredList = filteredList.OrderBy(x => int.Parse(x.date)).ToList();

                filteredList.Reverse();
                foreach (var order in filteredList)
                {
                    order.name = customer.CompanyName;
                }
                return View(model: filteredList);
            }
            else
            {
                return View(model: getLsOrd);
            }
         
            
        }
        public IActionResult ShowListByArt([FromQuery]string cli, [FromQuery]string art, [FromQuery]string dateBeg, [FromQuery]string dateEnd)
        {
            List<GetLSPreBP> getList = new GetLsPreClArt(cli, art).getLSPreAsync();

            var agentCode = JsonConvert.DeserializeObject<Agent>(HttpContext.Session.GetString("Logged")).Codice_ACG;

            var userList = Utils.getCustomers(agentCode);

            System.Diagnostics.Debug.WriteLine(userList.Count);
            List<GetLSPreBP> filteredList = getList.Where(x => userList.Any(y => y.AS400_CODE.ToString() == x.delId)).ToList();
            DateTime Beg = default(DateTime);
            DateTime End = default(DateTime);

            if (dateBeg != null)
            {
                Beg = DateTime.ParseExact(dateBeg, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }
            if (dateEnd != null)
            {
                End = DateTime.ParseExact(dateEnd, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }

            if (dateBeg != null && dateEnd == null)
            {
                filteredList = filteredList.Where(i => DateTime.ParseExact(i.getDate(), "dd/MM/yyyy", CultureInfo.InvariantCulture) > Beg).ToList();
            }
            if (dateBeg == null && dateEnd != null)
            {
                filteredList = filteredList.Where(i => DateTime.ParseExact(i.getDate(), "dd/MM/yyyy", CultureInfo.InvariantCulture) < End).ToList();
            }
            if (dateBeg != null && dateEnd != null)
            {
                filteredList = filteredList.Where(i => DateTime.ParseExact(i.getDate(), "dd/MM/yyyy", CultureInfo.InvariantCulture) >= Beg && DateTime.ParseExact(i.getDate(), "dd/MM/yyyy", CultureInfo.InvariantCulture) <= End).ToList();
            }


            filteredList = filteredList.OrderBy(x => int.Parse(x.date)).ToList();
            filteredList.Reverse();

            foreach(var order in filteredList)
            {
                var customer = userList.FirstOrDefault(x => x.AS400_CODE == int.Parse(order.delId));
                order.name = customer.CompanyName;
            }

            return View("ShowResultList", model: filteredList);
        }
        public IActionResult ShowResultPre([FromQuery]string pre)
        {
            List<GetPre> getPre = new GetPreService(pre, "http://2.229.69.115:8015/www/dacgi/WSGetPre.pgm").getPreAsync();
            if(getPre != null)
            {
                for (int i = 0; i < getPre.Count; i++)
                {
                    Product product = GetProduct(getPre[i].idProduct);
                    if(product != null)
                    {
                        getPre[i].productName = product.Name;
                    }
                   
                }
            }
            else
            {
                return View(model: null);
            }
            
            return View(model: getPre);
        }

        public string GetPreAsync([FromQuery]string pre)
        {
            List<GetPre> getPre = new GetPreService(pre, "http://2.229.69.115:8015/www/dacgi/WSGetPre.pgm").getPreAsync();
            
            for(int i = 0; i < getPre.Count; i++)
            {
                Product product = GetProduct(getPre[i].idProduct);
                if(product != null && getPre != null)
                {
                    getPre[i].productName = product.Name.Replace("\"", "");
                }
               

            }
            return JsonConvert.SerializeObject(getPre);
        }
        public Product GetProduct(string idArt)
        {
            SqlService service = new SqlService();
            service.init();
            try
            {
                SqlDataReader reader = service.query("SELECT dbo.GetProductForPDF(Product.Name) as Name FROM Product WHERE AS400_ID = '" + idArt + "'");

                Product product = null;

                while (reader.Read())
                {
                    Dictionary<String, String> column = Enumerable.Range(0, reader.FieldCount).ToDictionary(i => reader.GetName(i), i => reader.GetValue(i).ToString());
                    product = SQLMapping.MapProduct(column);

                }
                service.close();
                return product;
            }
            catch(Exception ex)
            {
                service.close();
                throw new System.ArgumentException(ex.Message);
            }
            
            
        }
        [HttpPost]
        public string GetInvoice([FromBody]PDFBody order)
        {
            using (var reader = new StreamReader(Request.Body))
            {
                var body = reader.ReadToEnd();
                PDFService service = new PDFService(order);

                return service.GetPDF().Result;
            }

            
        }
    }
}

Dashboard Microtech/Views/Preventivi/Search.cshtml
@{
    ViewData["Title"] = "Ricerca preventivi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<input type="hidden" id="agentcode" value="@Model.Codice_ACG" />

<div class="row mt-60">
    <div class="col-12">
        <div class="card">
            <div class="body-card">
                <div class="row">
                    <div class="col-6">
                        <label>Codice prodotto</label>
                        <input type="text" placeholder="Inserisci codice" name="prod" value="" id="prod">
                    </div>
                    <div class="col-6">
                        <label>Nome cliente</label>
                        <input type="text" placeholder="Inserisci nome" value="" name="cliente" id="autoComplete" class="typeahead">
                    </div>
                    <div class="col-6">
                        <label>Data inizio</label>
                        <div id="myDatepicker" class="input-group date">
                            <input type="text">
                            <span class="input-group-addon">
                            </span>
                        </div>
                    </div>
                    <div class="col-6">
                        <label>Data fine</label>
                        <div id="myDateEnd" class="input-group date">
                            <input type="text">
                            <span class="input-group-addon">
                            </span>
                        </div>
                    </div>
                    <div class="col-12">
                        <label>ID Preventivo</label>
                        <input type="text" placeholder="Inserisci ID preventivo" id="pre">
                    </div>
                    <div class="col-12 mt-20">
                        <a class="btn submit" href="@Url.Action("ShowResultList", "Preventivi")" data-target="prord">cerca</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Dashboard Microtech/Views/Preventivi/ShowResultList.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json;
@using Microtech_Core.Database.Models;
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Storico preventivi per ";
    ViewData["Customer"] = @Model[0].name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (@Model != null)
{
    <input type="hidden" id="clientId" value="@Model[0].delId" />
    <input type="hidden" id="agentcode" value='' />
    <input type="hidden" id="agentname" value='' />
    <input type="hidden" id="agentcell" value="" />
    <input type="hidden" id="agentemail" value="" />
    <script>
        var Model = @(Html.Raw(HttpContextAccessor.HttpContext.Session.GetString("Logged")));
        console.log(Model);
        document.getElementById("agentcode").value = Model["Codice_ACG"];
        document.getElementById("agentname").value = Model["Descrizione"].trimRight();
        document.getElementById("agentcell").value = Model["Cellulare"].trimRight();
        document.getElementById("agentemail").value = Model["Email"].trimRight();
    </script>

    <div class="row mt-60">
        <div class="col-12">
            <div class="card">
                <div class="body-card-w">
                    <h6 class="mb-30">Lista preventivi</h6>
                    <div class="table-responsive">
                        <table>
                            <tr>
                                <th>Stato</th>
                                <th>Numero</th>
                                <th>Data</th>
                                <th>Denominazione cliente</th>
                                <th>Importo</th>
                                <th>Azioni</th>
                            </tr>
                            <tbody>
                                @foreach (var i in @Model)
                                {
                                    <tr>
                                        <td>@i.status</td>
                                        <td>@i.id</td>
                                        <td>@i.getDate()</td>
                                        <td class="deliverNumber">@i.name</td>
                                        <td>@i.getValue() €</td>
                                        <td>
                                            <div class="dropdown dropdown-default">
                                                <button class="btn btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Azioni
                                                </button>
                                                <div class="dropdown-menu" style="width: 91.3438px; position: absolute; transform: translate3d(0px, -169px, 0px); top: 0px; left: 0px; will-change: transform;" x-placement="top-start">
                                                    <a class="dropdown-item" href="/preventivi/ShowResultPre?pre=@i.id">Dettagli</a>
                                                    @if ((string)Context.Request.Query["cli"] != "ALL")
                                                    {
                                                        <a href='/List/Crea?type=WPR&ordId=@i.id&editMode=true&ordCli=@Context.Request.Query["cli"]' class="dropdown-item">Modifica</a>
                                                    }
                                                    <!--<a href="https://desk.microtech.eu/template.html?" data-target="pre" data-ordId="@i.id" data-ordCli='@Context.Request.Query["cli"]' class="dropdown-item print">Stampa</a>-->
                                                    @if ((string)Context.Request.Query["cli"] != "ALL")
                                                    {
                                                        <a href='/List/Crea?type=WPR&ordId=@i.id&editMode=false&ordCli=@Context.Request.Query["cli"]' class="dropdown-item">Copia</a>
                                                    }
                                                    <a href="http://138.68.100.112/fatture/" data-target="pre" data-ordId="@i.id" data-ordCli='@Context.Request.Query["cli"]' class="dropdown-item pdf">
                                                        PDF
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    }
    else
    {
    <p>Ordine non trovato</p>
    }

Dashboard Microtech/Views/Preventivi/ShowResultPre.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Dettaglio preventivo";
    ViewData["Customer"] = @Model[0].id;
    ViewBag.Total = 0;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model != null)
{
    <input type="hidden" id="clientId" value="@Model[0].id" />
    <input type="hidden" id="agentcode" value='' />
    <input type="hidden" id="agentname" value='' />
    <input type="hidden" id="agentcell" value="" />
    <input type="hidden" id="agentemail" value="" />
    <script>
        var Model = @(Html.Raw(HttpContextAccessor.HttpContext.Session.GetString("Logged")));
        console.log(Model);
        document.getElementById("agentcode").value = Model["Codice_ACG"];
        document.getElementById("agentname").value = Model["Descrizione"].trimRight();
        document.getElementById("agentcell").value = Model["Cellulare"].trimRight();
        document.getElementById("agentemail").value = Model["Email"].trimRight();
    </script>
    <div class="row mt-60">
        <div class="col-12">
            <div class="card">
                <div class="body-card">
                    <div class="row">
                        <div class="col-6">

                            <ul>
                                <li>ID Cliente di spedizione: <span class="semi-bold">@Model[0].codSped</span></li>
                                <li>ID Cliente di fatturazione: <span class="semi-bold">@Model[0].codFatt</span></li>
                                <li>Nome cliente: @Model[0].cliSped</li>
                                <li id="totalPre">Subtotale: @Model[0].GetTotal() €</li>

                            </ul>
                            <br />
                            <a class="btn btn-sm" href="/List/Crea?type=WPR&ordId=@Model[0].id&editMode=true&ordCli=@Model[0].idDel">Modifica</a>
                            <a href="http://138.68.100.112/fatture/" data-target="pre" data-ordId="@Context.Request.Query["pre"]" data-ordCli='@Model[0].idDel' class="btn btn-sm pdf">
                                PDF
                            </a>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
    <div class="row mt-60">
        <div class="col-12">
            <div class="card">
                <div class="body-card-w">
                    <h6 class="mb-30">Lista prodotti ordine</h6>
                    <div class="table-responsive">
                        <table>
                            <tr>
                                <th>ID prod.</th>
                                <th>Nome articolo</th>
                                <th>Quantità articolo</th>
                                <th>Importo articolo</th>
                            </tr>
                            <tbody>
                                @foreach (var i in @Model)
                                {
                                    <tr>
                                        <td>@i.sku</td>
                                        <td>@i.productName</td>
                                        <td>@i.qty</td>
                                        <td>@Decimal.Parse(i.price.Replace(".", ",")).ToString("#.00") €</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    
                    <div class="mt-30 text-r"><button class="btn" type="button"></button></div>
                </div>
            </div>
        </div>
    </div>


}
else
{
    <h4>Preventivo non trovato o vuoto. Contattare l'amministratore.</h4>
}