Dashboard Microtech/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microtech_Core.Database;
using Microtech_Core.Database.Functions;
using Microtech_Core.Database.Models;
using Newtonsoft.Json;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Dashboard_Microtech.Controllers
{
    public class LoginController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Login([FromForm]LoginModel form)
        {
            string password = Hashing.Hash(form.password);
            string queryString = "SELECT TOP 1 * FROM Agenti_as400 WHERE Email = '" + form.code + "' AND Password = '" + password + "'";

            SqlService service = new SqlService();
            service.init();
            SqlDataReader reader = service.query(queryString);
            Agent agent;
            while (reader.Read())
            {
                Dictionary<String, String> column = Enumerable.Range(0, reader.FieldCount).ToDictionary(i => reader.GetName(i), i => reader.GetValue(i).ToString());
                agent = SQLMapping.mapAgent(column);

                HttpContext.Session.SetString("Logged", JsonConvert.SerializeObject(agent));
                if (agent != null)
                {
                    service.close();
                    return View("../Home/Index", JsonConvert.DeserializeObject<Agent>(HttpContext.Session.GetString("Logged")));
                }
                else
                {
                    service.close();
                    return View("Index");
                }

            }

            return View("Index");

        }
        
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("Logged");

            return View("Index");
        }
    }
}

Dashboard Microtech/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft_Core.Database.Models;
using Microtech_Core.Database;
using Microtech_Core.Database.Functions;
using Microtech_Core.Database.Models;
using Microtech_Core.WebServices.Services;
using Microtech_Core.WebServices.Services.Pojo;
using Newtonsoft.Json;

namespace Dashboard_Microtech.Views
{
    public class ProductsController : Controller
    {
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Logged") == null)
            {
                return View("../Login/Index");
            }
            return View("Search");
        }
        public IActionResult Search()
        {
            if (HttpContext.Session.GetString("Logged") == null)
            {
                return View("../Login/Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Result([FromQuery]int onlyAvailable, [FromQuery]int search, [FromQuery]int page)
        {
            if (HttpContext.Session.GetString("Logged") == null)
            {
                return View("../Login/Index");
            }
            SqlService dbInstance = new SqlService();
            dbInstance.init();
            int typeSearch = int.Parse((String)HttpContext.Request.Query["type"]);

            string sku = HttpContext.Request.Query["sku"];
            string filter;
            switch (search)
            {
                case 0:
                    filter = "SKU";
                    break;
                case 1:
                    filter = "Name";
                    break;
                default:
                    filter = "SKU";
                    break;
            }

            int offset = int.Parse(HttpContext.Request.Query["startItem"]);
            SqlDataReader reader;
            List<Product> records = new List<Product>();
            string queryString;

            if (filter == "Name")
            {
                string queryPart = "";
                if (sku.Contains(" "))
                {
                    string[] terms = sku.Split(' ');
                    for (int i = 0; i < terms.Length; i++)
                    {
                        if (i < terms.Length - 1)
                        {
                            queryPart += "\"" + terms[i] + "\" AND ";
                        }
                        else
                        {
                            queryPart += "\"" + terms[i] + "\"";
                        }

                    }
                }
                else
                {
                    queryPart = sku;
                }


                queryString = "SELECT P.*, A.GIACENZA FROM Product as P LEFT JOIN ProductAvailabilityMapping as A ON P.AS400_ID = A.AS400_ID WHERE CONTAINS(" + filter + ", '" + queryPart + "') AND DELETED = 1 ORDER BY A.GIACENZA DESC OFFSET " + offset + " ROWS FETCH NEXT 20 ROWS ONLY";
                //queryString = "SELECT P.*, A.GIACENZA FROM Product as P LEFT JOIN ProductAvailabilityMapping as A ON P.AS400_ID = A.AS400_ID WHERE FREETEXT(" + filter + ", '" + sku + "') AND DELETED = 1 ORDER BY A.GIACENZA DESC OFFSET " + offset + " ROWS FETCH NEXT 20 ROWS ONLY";
                System.Diagnostics.Debug.WriteLine(queryString);
            }
            else
            {
                switch (typeSearch)
                {
                    case 0:
                        queryString = "SELECT P.*, A.GIACENZA FROM Product as P LEFT JOIN ProductAvailabilityMapping as A ON P.AS400_ID = A.AS400_ID WHERE " + filter + " = '" + sku + "' AND DELETED = 1 ORDER BY A.GIACENZA DESC";
                        break;
                    case 1:
                        queryString = "SELECT P.*, A.GIACENZA FROM Product as P LEFT JOIN ProductAvailabilityMapping as A ON P.AS400_ID = A.AS400_ID WHERE " + filter + " LIKE '" + sku + "%' AND DELETED = 1 ORDER BY A.GIACENZA DESC";
                        break;
                    case 2:
                        queryString = "SELECT P.*, A.GIACENZA FROM Product as P LEFT JOIN ProductAvailabilityMapping as A ON P.AS400_ID = A.AS400_ID WHERE " + filter + " LIKE '%" + sku + "' AND DELETED = 1 ORDER BY A.GIACENZA DESC";
                        break;
                    case 3:
                        queryString = "SELECT P.*, A.GIACENZA FROM Product as P LEFT JOIN ProductAvailabilityMapping as A ON P.AS400_ID = A.AS400_ID WHERE " + filter + " LIKE '%" + sku + "%' AND DELETED = 1 ORDER BY A.GIACENZA DESC";
                        break;
                    case 4:
                        queryString = "SELECT ProductCategoryMapping.ProductFK, ProductCategoryMapping.CategoryFK, Product.* FROM ProductCategoryMapping JOIN Product ON ProductCategoryMapping.ProductFK = Product.PK WHERE CategoryFK = " + sku;
                        break;
                    default:
                        queryString = null;
                        break;
                }
            }
            reader = dbInstance.query(queryString);
            if (reader != null)
            {
                while (reader.Read())
                {
                    Dictionary<String, String> column = Enumerable.Range(0, reader.FieldCount).ToDictionary(i => reader.GetName(i), i => reader.GetValue(i).ToString());

                    Product product = SQLMapping.MapProduct(column);

                    if (!CheckSample(product.SKU).Result)
                    {
                        records.Add(product);
                    }


                }

                reader.Close();
            }

            records = records.OrderBy(x => x.GIACENZA).ToList();
            records.Reverse();
            dbInstance.close();
            return View(records);
        }

        public PartialViewResult getProductView()
        {
            return PartialView("Search");
        }
        public async Task<String> GetProducts([FromQuery]int startItem, [FromQuery]string param, [FromQuery]int searchtype)
        {
            if (searchtype == 0)
            {
                var queryString = "SELECT P.*, A.GIACENZA FROM Product as P LEFT JOIN ProductAvailabilityMapping as A ON P.AS400_ID = A.AS400_ID WHERE SKU = '" + param + "' AND DELETED = 1 ORDER BY A.GIACENZA DESC OFFSET " + startItem + " ROWS FETCH NEXT 20 ROWS ONLY";

                SqlDataReader reader;
                SqlService dbInstance = new SqlService();
                dbInstance.init();
                List<Product> records = new List<Product>();
                reader = dbInstance.query(queryString);
                System.Diagnostics.Debug.WriteLine(queryString);
                if (reader != null)
                {
                    while (reader.Read())
                    {
                        Dictionary<String, String> column = Enumerable.Range(0, reader.FieldCount).ToDictionary(i => reader.GetName(i), i => reader.GetValue(i).ToString());

                        Product product = SQLMapping.MapProduct(column);

                        if (!CheckSample(product.SKU).Result)
                        {
                            records.Add(product);
                        }


                    }

                    reader.Close();
                }

                records = records.OrderBy(x => x.GIACENZA).ToList();
                records.Reverse();

                return JsonConvert.SerializeObject(records);
            }
            else
            {
                string queryPart = "";
                if (param.Contains(" "))
                {
                    string[] terms = param.Split(' ');
                    for (int i = 0; i < terms.Length; i++)
                    {
                        if (i < terms.Length - 1)
                        {
                            queryPart += "\"" + terms[i] + "\" AND ";
                        }
                        else
                        {
                            queryPart += "\"" + terms[i] + "\"";
                        }

                    }
                }
                else
                {
                    queryPart = param;
                }

                string query = "SELECT DISTINCT P.*, A.GIACENZA FROM Product as P LEFT JOIN ProductAvailabilityMapping as A ON P.AS400_ID = A.AS400_ID WHERE CONTAINS(Name, '" + queryPart + "') AND DELETED = 1 ORDER BY A.GIACENZA DESC OFFSET " + startItem + " ROWS FETCH NEXT 20 ROWS ONLY";

                SqlService dbInstance = new SqlService();
                dbInstance.init();
                SqlDataReader reader = dbInstance.query(query);
                List<Product> records = new List<Product>();
                if (reader != null)
                {
                    while (reader.Read())
                    {
                        Dictionary<String, String> column = Enumerable.Range(0, reader.FieldCount).ToDictionary(i => reader.GetName(i), i => reader.GetValue(i).ToString());
                        Product product = SQLMapping.MapProduct(column);
                        if(!CheckSampleSync(product.SKU)) records.Add(product);


                    }

                    reader.Close();
                }
                dbInstance.close();

                return JsonConvert.SerializeObject(records);
            }



        }
        public async Task<String> getResultAsync([FromQuery]int itemPage, [FromQuery]int onlyAvailable, [FromQuery]int search)
        {
            SqlService dbInstance = new SqlService();
            dbInstance.init();
            string sku = HttpContext.Request.Query["sku"];
            int typeSearch = int.Parse((String)HttpContext.Request.Query["type"]);
            int offset = int.Parse(HttpContext.Request.Query["startItem"]);
            string filter;
            switch (search)
            {

Dashboard Microtech/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json.Linq;
@using Newtonsoft.Json;
@using Microtech_Core.Database.Models;

@inject IHttpContextAccessor HttpContextAccessor;
@{
    var pageName = ViewContext.RouteData.Values["controller"].ToString();
    var category = Context.Request.Path.Value.Split('/')[1];
    var route = "";
    if (Context.Request.Path.Value.Split('/').Length > 2)
    {
        route = Context.Request.Path.Value.Split('/')[2];

    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">

    <link rel="shortcut icon" id="favicon" href="/dist/img/favicon.png">

    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="copyright" content="">

    <script src="/lib/jquery/jquery-2.2.4.min.js"></script>
    <script src="~/lib/bootstrap/popper.min.js"></script>

    <script src="/lib/bootstrap/bootstrap.min.js"></script>
    <script src="/lib/jcf/jcf.min.js"></script>
    <link rel="stylesheet" href="/lib/datepicker/datepicker3.css">
    <link rel="stylesheet" href="/dist/css/style.css">

    <link rel="stylesheet" href="/lib/fontawesome/css/all.min.css">
    <link href="/css/datepicker3.css" rel="stylesheet" />
    <link href="/css/daterangepicker-bs3.css" rel="stylesheet" />

    <script src="/js/bootstrap-datepicker.js"></script>
    <script src="/js/typeahead.bundle.min.js" type="text/javascript"></script>
    <script src="~/js/handlebars.js"></script>
    <script src="~/src/js/adem.js"></script>
    <script src="~/src/js/adem_alert.min.js"></script>
    <!-- Only for development -->

    <script src="/src/js/include-partials.js"></script>
    <script src="/lib/datepicker/daterangepicker.js"></script>
    <!--[if IE]>
    <script type="text/javascript" src="lib/html5shiv/html5shiv.min.js"></script><![endif]-->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Microtech Desk</title>

</head>
<body class="fixed-header dashboard menu-pin">

    <div class="hd-mobile">
        <div class="nav-btn">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
        <img src="/dist/img/logo.svg" alt="logo" class="logo-hd">
    </div>
    <header class="header-main">
        <a href="@this.Url.Action("Index", "Home")">
            <img src="/dist/img/logo.svg" alt="logo" class="logo-hd">
        </a>
        <nav class="nav-side">
            <ul>
                <li class="menu-item-has-children @(category.ToLower() == "list" ? "show" : "")">
                    <a href="#">Azioni</a>
                    <ul class="display-none" style="@(category.ToLower() == "list" ? "display:block" : "")">
                        <li class="@(pageName == "List" ? "active" : "")"><a href="/list/crea?type=WPR">Nuovo preventivo</a></li>
                        <li class="@(pageName == "Archive" ? "active" : "")"><a href="/archive/SearchOrderClients?editMode=true&type=WOP">Modifica conto a scalare</a></li>

                        @if (HttpContextAccessor.HttpContext.Session.GetString("Logged").Contains("A01") || HttpContextAccessor.HttpContext.Session.GetString("Logged").Contains("C01") || HttpContextAccessor.HttpContext.Session.GetString("Logged").Contains("C02"))
                        {
                            <li><a href="/list/crea?type=WLS">Nuova offerta dipartimentale</a></li>
                        }

                    </ul>
                </li>
                <li class="menu-item-has-children @(category.ToLower() == "archive" || category.ToLower() == "preventivi" ? "show" : "")">
                    <a href="#">Archivio</a>
                    <ul style="@(category.ToLower() == "archive" || category.ToLower() == "preventivi" ? "display:block" : "")" class="display-none">
                        <li class="@(route == "SearchOrderClients" ? "active" : "")"><a href="@this.Url.Action("SearchOrderClients", "Archive")">Ordini clienti</a></li>
                        <li class="@(pageName == "Preventivi" ? "active" : "")"><a href="/preventivi">Preventivi</a></li>
                        <li class="@(route == "listsearch" ? "active" : "")"><a href="/archive/listsearch">Offerta dipartimentale</a></li>
                    </ul>
                </li>
                <li><a href="@this.Url.Action("Search", "Products")">Prodotti</a></li>
                <li class="menu-item-has-children @(category.ToLower() == "anagrafica" ? "show" : "")">
                    <a href="">Anagrafica</a>
                    <ul class="display-none" style="@(category.ToLower() == "anagrafica" ? "display:block" : "")">
                        <li class="@(route == "Spedizione" ? "active" : "")"><a href="@this.Url.Action("Spedizione", "Anagrafica")">Clienti</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children @(category.ToLower() == "sicurezza" ? "show" : "")">
                    <a href="">Sicurezza</a>
                    <ul class="display-none" style="@(category.ToLower() == "sicurezza" ? "display:block" : "")">
                        <li class="@(route == "password" ? "active" : "")"><a href="/sicurezza/password">Cambio password</a></li>
                    </ul>
                </li>
                @{
                    Microtech_Core.Database.Models.Agent agent = JsonConvert.DeserializeObject<Microtech_Core.Database.Models.Agent>(HttpContextAccessor.HttpContext.Session.GetString("Logged"));
                }
                @if (HttpContextAccessor.HttpContext.Session.GetString("Logged").Contains("A01") || HttpContextAccessor.HttpContext.Session.GetString("Logged").Contains("C01") || HttpContextAccessor.HttpContext.Session.GetString("Logged").Contains("C02"))
                {
                    <li class="menu-item-has-children">
                        <a href="">Gestione</a>
                        <ul class="display-none">
                            <li><a href="/amministrazione/agenti">Gestione agenti</a></li>
                            <li><a href="/amministrazione/discount">Gestione sconti</a></li>
                            <li><form name="importa_clienti" action="http://2.229.69.115:10080/ImportaClienti" method="POST"><input type="hidden" name="codage" value="@agent.Codice_ACG" /><a href="javascript: document.importa_clienti.submit()">Importa clienti</a></form></li>
                            <li><form name="accettazione_clienti" action="http://2.229.69.115:10080/ImportaClienti/menu.php" method="POST"><input type="hidden" name="codage" value="@agent.Codice_ACG" /><a href="javascript: document.accettazione_clienti.submit()">Importa clienti interni</a></form></li>
                        </ul>


                    </li>
                }
            </ul>
        </nav>
        <a type="button" class="btn btn-sm btn-logout logout" href="/login/Logout"><i class="fal fa-power-off"></i>Logout</a>
    </header>

    <section class="bx-page">
        @if (pageName != "Login" && pageName != "Home")
        {
            <a href="javascript: history.go(-1)" class="btn btn-outline btn-sm btn-back"><i class="fal fa-chevron-left"></i> Indietro</a>
        }
        <div class="row">
            <div class="col-12">
                <h2>
                    @ViewData["Title"] @if (ViewData["Customer"] != null)
                    {<span>@ViewData["Customer"]</span>}
                </h2>
                <time>@DateTime.Now.ToString("dd MMMM yyyy", new System.Globalization.CultureInfo("it-IT")) - ore @DateTime.Now.ToString("HH:mm", new System.Globalization.CultureInfo("it-IT"))</time>
            </div>
        </div>

        @RenderBody()

        <div class="footer">Copyright © 2019 Emmemedia All right reserved.</div>
    </section>

    @RenderSection("Scripts", required: false)
    <script type="text/javascript" src="~/js/site.js"></script>
</body>
</html>

Dashboard Microtech/Views/Shared/_Login.cshtml
<!doctype html>
<!--
=====================================
Made with Adem ======================
=====================================
 ______  _____   ______  __    __
/\  __ \/\  __-./\  ___\/\ "-./  \
\ \  __ \ \ \/\ \ \  __\\ \ \-./\ \
 \ \_\ \_\ \____-\ \_____\ \_\ \ \_\
  \/_/\/_/\/____/ \/_____/\/_/  \/_/
=====================================
=====================================
=====================================
-->
<html lang="it" xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">
    <title>Accedi - Microtech</title>

    <link rel="shortcut icon" id="favicon" href="dist/img/favicon.png">

    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="copyright" content="">

    <script src="/lib/jquery/jquery-2.2.4.min.js"></script>
    <script src="/lib/bootstrap/bootstrap.min.js"></script>
    <script src="/lib/jcf/jcf.min.js"></script>

    <link rel="stylesheet" href="/dist/css/style.css">

    <link rel="stylesheet" href="/lib/fontawesome/css/all.min.css">

    <script src="/src/js/adem.js"></script>


    <!--[if IE]><script type="text/javascript" src="lib/html5shiv/html5shiv.min.js"></script><![endif]-->

</head>

<body>
    <div class="container">
        <main>
            <section class="bx-home">
                <div class="w-100">
                    <div class="row">
                        <div class="col-8 col-12-md mx-auto">
                            <img src="/dist/img/logo-negative.svg" alt="">
                            <h2 class="mt-60 line">Microtech, la scelta logica.</h2>
                            <p>Oltre 5 milioni di prodotti di aziende di prestigio nel settore.</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4 col-12-md mx-auto">
                            @RenderBody()
                        </div>
                    </div>
                    <div class="bx-copy">Copyright © 2019 Emmemedia All right reserved.</div>
            </section>
        </main>
    </div>

</body>
</html>